namespace Splines.Curves;

public interface IParamSplineSegment<out P, M>
{
    /// <summary>The curve generated by the control points</summary>
    P Curve { get; }

    /// <summary>The matrix containing the control points of this spline segment</summary>
    M PointMatrix { get; set; }
}
